import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { expectFrontmatter, readEventFrontmatter } from "@real1ty-obsidian-plugins/testing/e2e";

import { expect, test } from "../../fixtures/electron";
import { createEventViaModal, formatLocalDate, openCalendarReady } from "./events-helpers";

test.describe("recurring events", () => {
	test("weekly Mon/Wed/Fri writes the correct RRule + RRuleSpec", async ({ obsidian }) => {
		await openCalendarReady(obsidian.page);

		// Schedule the source close to today so the default month view includes it.
		const tomorrowDate = new Date();
		tomorrowDate.setDate(tomorrowDate.getDate() + 1);
		const tomorrow = formatLocalDate(tomorrowDate);

		const relativePath = await createEventViaModal(obsidian, {
			title: "Weekly Review",
			start: `${tomorrow}T09:00`,
			end: `${tomorrow}T10:00`,
			recurring: {
				rruleType: "weekly",
				weekdays: ["monday", "wednesday", "friday"],
			},
		});
		const fm = readEventFrontmatter(obsidian.vaultDir, relativePath);
		expect(fm["RRule"]).toBe("weekly");
		const spec = String(fm["RRuleSpec"] ?? "");
		expect(spec).toContain("monday");
		expect(spec).toContain("wednesday");
		expect(spec).toContain("friday");
	});

	test("custom interval every 2 days persists to frontmatter", async ({ obsidian }) => {
		await openCalendarReady(obsidian.page);

		const relativePath = await createEventViaModal(obsidian, {
			title: "Workout",
			start: "2026-05-10T07:00",
			end: "2026-05-10T07:30",
			recurring: {
				rruleType: "custom",
				customFreq: "DAILY",
				customInterval: 2,
			},
		});
		const fm = readEventFrontmatter(obsidian.vaultDir, relativePath);
		// Custom DSL stores a frequency/interval marker in the rrule property.
		expect(String(fm["RRule"] ?? "")).toMatch(/2/);
	});

	test("Skip toggled on a physical instance hides it from render", async ({ obsidian }) => {
		// Seed a physical instance of a weekly series directly on disk. The
		// create-event path gives us the source event; a physical instance
		// would normally be generated by the recurrence engine, but a seeded
		// file with `Skip: true` still exercises the same filter pipeline.
		const instancePath = "Events/Skipped Instance.md";
		writeFileSync(
			join(obsidian.vaultDir, instancePath),
			`---
Start Date: 2026-05-11T09:00
End Date: 2026-05-11T10:00
Skip: true
---

# Skipped Instance
`,
			"utf8"
		);
		await obsidian.page.waitForTimeout(500);
		await openCalendarReady(obsidian.page);
		await obsidian.page.waitForTimeout(500);

		expectFrontmatter(obsidian.vaultDir, instancePath, { Skip: true });

		const skippedBlock = obsidian.page.locator(".fc-event", { hasText: "Skipped Instance" });
		const skippedVisible = await skippedBlock.count();
		expect(skippedVisible).toBe(0);
	});
});
