import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		{
			type: "doc",
			id: "intro",
			label: "Prisma Calendar",
		},
		"installation",
		"quickstart",
		"videos",
		"gallery",
		{
			type: "category",
			label: "Features",
			collapsible: true,
			items: [
				"features/overview",
				"features/multiple-calendars",
				"features/folder-scanning",
				"features/templater",
				"features/color-rules",
				"features/categories",
				"features/filtering",
				"features/statistics",
				"features/time-tracker",
				"features/global-events-management",
				"features/notifications",
				"features/holidays",
				"features/event-previews",
				"features/event-icons",
				"features/zettelid-naming",
				"features/batch-operations",
				"features/event-skipping",
				"features/untracked-events",
				"features/undo-redo",
				"features/recurring-dsl",
				"features/event-series",
				"features/virtual-events",
				"features/integrations",
				"features/hotkeys",
				"features/programmatic-api",
			],
		},
		"configuration",
		"faq",
		"troubleshooting",
		"contributing",
		"support",
		"changelog",
	],
};

export default sidebars;
