/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source: NotesManipulator/api-contract.json
 * Regenerate: pnpm --filter @real1ty-obsidian-plugins run emit-external-apis
 *
 * Public surface: NotesManipulatorApi + window augmentation. Every method
 * returns Promise<T> regardless of whether the producer's handler is sync
 * or async — see docs/decisions/2026-05-15-external-apis-shared-emission.md.
 */

export interface NotesManipulatorExecutePresetInput {
	/**
	 * User-visible preset name. Matched case-sensitively against every preset list.
	 */
	presetName: string;
}
/**
 * Structured result envelope. Mirrors the `moveEventToCalendar` shape from Prisma-Calendar so cross-plugin consumers see a uniform success/reason/error contract.
 */
export interface NotesManipulatorExecutePresetOutput {
	/**
	 * Human-readable failure detail. Always present when `success === false`.
	 */
	error?: string;
	/**
	 * Present when `success === false`. Distinguishes the three failure paths so callers can branch on the cause.
	 */
	reason?: "no-pro" | "unknown-preset" | "executor-failed";
	/**
	 * True only when the preset ran end-to-end and at least one operation succeeded.
	 */
	success: boolean;
}
/**
 * Flattened list of every configured preset across all mode buckets.
 */
export type NotesManipulatorListPresetsOutput = {
	/**
	 * Stable internal id used for cross-session references.
	 */
	id: string;
	/**
	 * Discriminator that selects which preset executor handles the run.
	 */
	mode: "editProperties" | "deleteFiles" | "orderProperties" | "editContent" | "renameFiles";
	/**
	 * Display name; the unique key callers pass to executePreset.
	 */
	name: string;
}[];
/**
 * True if the most recently undone run was re-applied. False when the redo stack is empty.
 */
export type NotesManipulatorRedoOutput = boolean;
/**
 * True if a previous run was reverted. False when the undo stack is empty.
 */
export type NotesManipulatorUndoOutput = boolean;
export interface NotesManipulatorApi {
	executePreset(input: NotesManipulatorExecutePresetInput): Promise<NotesManipulatorExecutePresetOutput>;
	listPresets(): Promise<NotesManipulatorListPresetsOutput>;
	redo(): Promise<NotesManipulatorRedoOutput>;
	undo(): Promise<NotesManipulatorUndoOutput>;
}

declare global {
	interface Window {
		NotesManipulator?: NotesManipulatorApi;
	}
}
