/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source: NotesManipulator/api-contract.json
 * Regenerate: pnpm --filter @real1ty-obsidian-plugins run emit-external-apis
 *
 * Public surface: NotesManipulatorApi + window augmentation. Every method
 * returns Promise<T> regardless of whether the producer's handler is sync
 * or async — see docs/decisions/2026-05-15-external-apis-shared-emission.md.
 */

export interface NotesManipulatorExecutePresetInput {
	/**
	 * User-visible preset name. Matched case-sensitively against every preset list.
	 */
	presetName: string;
}
/**
 * True if the preset ran to completion. False on Pro-gate, unknown name, or executor failure.
 */
export type NotesManipulatorExecutePresetOutput = boolean;
/**
 * Flattened list of every configured preset across all mode buckets.
 */
export type NotesManipulatorListPresetsOutput = {
	/**
	 * Stable internal id used for cross-session references.
	 */
	id: string;
	/**
	 * Discriminator that selects which preset executor handles the run.
	 */
	mode: "editProperties" | "deleteFiles" | "orderProperties" | "editContent" | "renameFiles";
	/**
	 * Display name; the unique key callers pass to executePreset.
	 */
	name: string;
}[];
/**
 * True if the most recently undone run was re-applied. False when the redo stack is empty.
 */
export type NotesManipulatorRedoOutput = boolean;
/**
 * True if a previous run was reverted. False when the undo stack is empty.
 */
export type NotesManipulatorUndoOutput = boolean;
export interface NotesManipulatorApi {
	executePreset(input: NotesManipulatorExecutePresetInput): Promise<NotesManipulatorExecutePresetOutput>;
	listPresets(): Promise<NotesManipulatorListPresetsOutput>;
	redo(): Promise<NotesManipulatorRedoOutput>;
	undo(): Promise<NotesManipulatorUndoOutput>;
}

declare global {
	interface Window {
		NotesManipulator?: NotesManipulatorApi;
	}
}
