/**
 * AUTOGENERATED — DO NOT EDIT.
 *
 * Source: Prisma-Calendar/api-contract.json
 * Regenerate: pnpm --filter @real1ty-obsidian-plugins run emit-external-apis
 *
 * Public surface: PrismaCalendarApi + window augmentation. Every method
 * returns Promise<T> regardless of whether the producer's handler is sync
 * or async — see docs/decisions/2026-05-15-external-apis-shared-emission.md.
 */

export interface PrismaCalendarActivateInput {
	key: string;
}
export interface PrismaCalendarAddZettelIdToActiveNoteInput {
	calendarId?: string;
}
export type PrismaCalendarAddZettelIdToActiveNoteOutput = boolean;
export interface PrismaCalendarAiQueryInput {
	calendarId?: string;
	customPromptIds?: string[];
	execute?: boolean;
	message: string;
	mode?: "query" | "manipulation" | "planning";
}
export interface PrismaCalendarAiQueryOutput {
	error?: string;
	executionResult?: {
		failed: number;
		succeeded: number;
		total: number;
	};
	mode?: "query" | "manipulation" | "planning";
	operations?: (
		| {
				allDay?: boolean;
				categories?: string[];
				end: string;
				location?: string;
				participants?: string[];
				start: string;
				title: string;
				type: "create";
		  }
		| {
				allDay?: boolean;
				categories?: string[];
				end?: string;
				filePath: string;
				location?: string;
				participants?: string[];
				start?: string;
				title?: string;
				type: "edit";
		  }
		| {
				filePath: string;
				type: "delete";
		  }
	)[];
	response?: string;
	success: boolean;
	validationErrors?: string[];
}
export interface PrismaCalendarBatchDeleteInput {
	calendarId?: string;
	filePaths: string[];
}
export type PrismaCalendarBatchDeleteOutput = boolean;
export interface PrismaCalendarBatchMarkAsDoneInput {
	calendarId?: string;
	filePaths: string[];
}
export type PrismaCalendarBatchMarkAsDoneOutput = boolean;
export interface PrismaCalendarBatchMarkAsUndoneInput {
	calendarId?: string;
	filePaths: string[];
}
export type PrismaCalendarBatchMarkAsUndoneOutput = boolean;
export interface PrismaCalendarBatchToggleSkipInput {
	calendarId?: string;
	filePaths: string[];
}
export type PrismaCalendarBatchToggleSkipOutput = boolean;
export interface PrismaCalendarCloneEventInput {
	calendarId?: string;
	filePath: string;
	offsetMs?: number;
}
export type PrismaCalendarCloneEventOutput = string | null;
export interface PrismaCalendarConvertFileToEventInput {
	allDay?: boolean;
	calendarId?: string;
	categories?: string[];
	end?: string;
	filePath: string;
	frontmatter?: {
		[k: string]: unknown;
	};
	location?: string;
	markAsDone?: boolean;
	participants?: string[];
	skip?: boolean;
	start?: string;
	title?: string;
}
export type PrismaCalendarConvertFileToEventOutput = boolean;
export interface PrismaCalendarCreateEventInput {
	allDay?: boolean;
	calendarId?: string;
	categories?: string[];
	end?: string;
	frontmatter?: {
		[k: string]: unknown;
	};
	location?: string;
	markAsDone?: boolean;
	participants?: string[];
	skip?: boolean;
	start?: string;
	title: string;
}
export type PrismaCalendarCreateEventOutput = string | null;
export interface PrismaCalendarCreateUntrackedEventInput {
	calendarId?: string;
	title: string;
}
export type PrismaCalendarCreateUntrackedEventOutput = string | null;
export interface PrismaCalendarDeleteEventInput {
	calendarId?: string;
	filePath: string;
}
export type PrismaCalendarDeleteEventOutput = boolean;
export interface PrismaCalendarDuplicateCurrentEventInput {
	calendarId?: string;
}
export type PrismaCalendarDuplicateCurrentEventOutput = boolean;
export interface PrismaCalendarEditEventInput {
	allDay?: boolean;
	calendarId?: string;
	categories?: string[];
	end?: string;
	filePath: string;
	frontmatter?: {
		[k: string]: unknown;
	};
	location?: string;
	markAsDone?: boolean;
	participants?: string[];
	skip?: boolean;
	start?: string;
	title?: string;
}
export type PrismaCalendarEditEventOutput = boolean;
export interface PrismaCalendarGetAllEventsInput {
	calendarId?: string;
}
export type PrismaCalendarGetAllEventsOutput = {
	allDay: boolean;
	categories?: string[];
	color?: string;
	end?: string;
	filePath: string;
	icon?: string;
	instanceDate?: string;
	location?: string;
	participants?: string[];
	rruleId?: string;
	rruleType?: string;
	skipped: boolean;
	start?: string;
	status?: string;
	title: string;
	type: "timed" | "allDay" | "untracked";
	virtualKind: string;
}[];
export interface PrismaCalendarGetCalendarInfoInput {
	calendarId?: string;
}
export type PrismaCalendarGetCalendarInfoOutput = {
	calendarId: string;
	directory: string;
	enabled: boolean;
	eventCount: number;
	name: string;
	untrackedEventCount: number;
} | null;
export interface PrismaCalendarGetCategoriesInput {
	calendarId?: string;
}
export type PrismaCalendarGetCategoriesOutput = {
	color: string;
	name: string;
}[];
export interface PrismaCalendarGetEventByPathInput {
	calendarId?: string;
	filePath: string;
}
export type PrismaCalendarGetEventByPathOutput = {
	allDay: boolean;
	categories?: string[];
	color?: string;
	end?: string;
	filePath: string;
	icon?: string;
	instanceDate?: string;
	location?: string;
	participants?: string[];
	rruleId?: string;
	rruleType?: string;
	skipped: boolean;
	start?: string;
	status?: string;
	title: string;
	type: "timed" | "allDay" | "untracked";
	virtualKind: string;
} | null;
export interface PrismaCalendarGetEventsInput {
	calendarId?: string;
	end: string;
	start: string;
}
export type PrismaCalendarGetEventsOutput = {
	allDay: boolean;
	categories?: string[];
	color?: string;
	end?: string;
	filePath: string;
	icon?: string;
	instanceDate?: string;
	location?: string;
	participants?: string[];
	rruleId?: string;
	rruleType?: string;
	skipped: boolean;
	start?: string;
	status?: string;
	title: string;
	type: "timed" | "allDay" | "untracked";
	virtualKind: string;
}[];
export interface PrismaCalendarGetSettingsInput {
	calendarId?: string;
}
export type PrismaCalendarGetSettingsOutput = {
	activeTab?: {
		colorOverrides?: {
			[k: string]: string;
		};
		groupState?: {
			[k: string]: {
				childColorOverrides?: {
					[k: string]: string;
				};
				childIconOverrides?: {
					[k: string]: string;
				};
				childRenames?: {
					[k: string]: string;
				};
				visibleChildIds?: string[];
			};
		};
		iconOverrides?: {
			[k: string]: string;
		};
		renames?: {
			[k: string]: string;
		};
		showSettingsButton?: boolean;
		visibleTabIds?: string[];
	};
	/**
	 * Maximum height in pixels for all-day events section before overflow
	 */
	allDayEventHeight: number;
	/**
	 * Frontmatter property name for all-day flag
	 */
	allDayProp: string;
	/**
	 * Frontmatter property name to mark events as already notified
	 */
	alreadyNotifiedProp: string;
	/**
	 * Show a confirmation modal before propagating frontmatter changes to instances. Allows you to review changes before applying them.
	 */
	askBeforePropagatingFrontmatter: boolean;
	/**
	 * Show a confirmation modal before propagating frontmatter changes to category series members. Allows you to review changes before applying them.
	 */
	askBeforePropagatingToCategorySeries: boolean;
	/**
	 * Show a confirmation modal before propagating frontmatter changes to name series members. Allows you to review changes before applying them.
	 */
	askBeforePropagatingToNameSeries: boolean;
	autoAssignCategoryByIncludes: SubstringMatchingForCategoriesAndPresets;
	autoAssignCategoryByName: AutoAssignWhenNameMatchesCategory;
	autoAssignZettelId: AutoAssignZettelID;
	basesViewProperties: AdditionalProperties;
	basesViewType: ViewType;
	batchActionButtons: (
		| "batchSelectAll"
		| "batchClear"
		| "batchDuplicate"
		| "batchMoveBy"
		| "batchMarkAsDone"
		| "batchMarkAsNotDone"
		| "batchCategories"
		| "batchFrontmatter"
		| "batchCloneNext"
		| "batchClonePrev"
		| "batchMoveNext"
		| "batchMovePrev"
		| "batchOpenAll"
		| "batchSkip"
		| "batchMakeVirtual"
		| "batchMakeReal"
		| "batchDelete"
	)[];
	/**
	 * Frontmatter property name for break time in minutes (subtracted from event duration in statistics, supports decimals)
	 */
	breakProp: string;
	caldavProp: CalDAVProperty;
	/**
	 * Auto-computed display title property (wiki link with ZettelID stripped from filename). Used for clean rendering in planning system and Bases views. The value is always kept up to date automatically.
	 */
	calendarTitleProp: string;
	capacityTrackingEnabled: EnableCapacityTracking;
	categoryAssignmentPresets: {
		categories: string[];
		eventName: string;
		id: string;
	}[];
	/**
	 * Frontmatter property name for event categories (used for grouping in statistics)
	 */
	categoryProp: string;
	/**
	 * Controls how many color rule matches are applied to each event. Off: no coloring. 1: single color (default). 2-5: split the event width into equal segments, each colored by a successive matching rule.
	 */
	colorMode: "1" | "2" | "3" | "4" | "5" | "off";
	colorRules: {
		color: string;
		enabled: boolean;
		expression: string;
		id: string;
	}[];
	connectionArrowSize: ArrowheadSize;
	connectionColor: ArrowColor;
	connectionStrokeWidth: LineThickness;
	contextMenuItems: (
		| "enlarge"
		| "preview"
		| "goToSource"
		| "editSourceEvent"
		| "viewEventGroups"
		| "viewNameSeries"
		| "viewCategorySeries"
		| "viewRecurringSeries"
		| "editEvent"
		| "assignCategories"
		| "assignPrerequisites"
		| "duplicateEvent"
		| "moveBy"
		| "moveToCalendar"
		| "markDone"
		| "moveToNextWeek"
		| "cloneToNextWeek"
		| "moveToPreviousWeek"
		| "cloneToPreviousWeek"
		| "fillStartTimeNow"
		| "fillEndTimeNow"
		| "fillStartTimePrevious"
		| "fillEndTimeNext"
		| "deleteEvent"
		| "skipEvent"
		| "openFile"
		| "openFileNewWindow"
		| "toggleRecurring"
		| "triggerStopwatch"
		| "duplicateRemainingWeekDays"
		| "makeVirtual"
		| "makeReal"
		| "makeUntracked"
	)[];
	contextMenuState?: {
		colorOverrides?: {
			[k: string]: string;
		};
		iconOverrides?: {
			[k: string]: string;
		};
		renames?: {
			[k: string]: string;
		};
		sectionOverrides?: {
			[k: string]: string;
		};
		showSettingsButton?: boolean;
		visibleItemIds?: string[];
	};
	/**
	 * Overrides the status property for manual mark-as-done actions. Format: "propertyName value" (e.g., "archived true"). When set, this is used instead of the status property. Leave empty to use the default behavior.
	 */
	customDoneProperty: string;
	/**
	 * Overrides what happens when marking as undone. Format: "propertyName value" (e.g., "archived false"). Requires "Custom done property" to be configured. If empty, the custom done property key is removed on undone instead.
	 */
	customUndoneProperty: string;
	dailyStatsGridState?: unknown;
	dashboardGridState?: {
		[k: string]: unknown;
	};
	/**
	 * Frontmatter property name for all-day events (date only, no time)
	 */
	dateProp: string;
	dayCellColoring: DayCellColoring;
	/**
	 * Frontmatter property name for per-event notification days (all-day events)
	 */
	daysBeforeProp: string;
	defaultAggregationMode: DefaultGroupingMode;
	defaultDaysBefore?: AllDayEventsDaysBefore;
	defaultDurationMinutes: DefaultDurationMinutes;
	defaultMinutesBefore?: TimedEventsMinutesBefore;
	defaultMobileView: DefaultMobileView;
	defaultNodeColor: DefaultEventColor;
	defaultPresetId?: string;
	defaultView: DefaultView;
	density: DisplayDensity;
	desktopMaxEventsPerDay: DesktopEventsPerDay;
	/**
	 * Folder to scan for events and create new events in
	 */
	directory: {
		[k: string]: unknown;
	};
	/**
	 * Value to set in the status property when marking an event as done
	 */
	doneValue: string;
	/**
	 * Delay in milliseconds before scrolling when dragging events near the edge
	 */
	dragEdgeScrollDelayMs: number;
	dualDailyGridState?: unknown;
	enabled: boolean;
	/**
	 * Show preview of event notes when hovering over events
	 */
	enableEventPreview: boolean;
	/**
	 * Use left/right arrow keys to navigate between intervals. Automatically disabled when search or expression filter inputs are focused.
	 */
	enableKeyboardNavigation: boolean;
	/**
	 * Track name-based event series (groups events sharing the same title). Used for name series propagation and series views. Disable to reduce memory usage in large vaults.
	 */
	enableNameSeriesTracking: boolean;
	/**
	 * Enable event notifications. When disabled, all notification settings below are ignored.
	 */
	enableNotifications: boolean;
	/**
	 * Frontmatter property name for event end date/time (for timed events)
	 */
	endProp: string;
	eventMaxStack: EventStackLimit;
	eventOverlap: AllowEventOverlap;
	eventPresets: {
		allDay?: boolean;
		breakMinutes?: number;
		categories?: string;
		createdAt: number;
		customProperties?: {
			[k: string]: unknown;
		};
		futureInstancesCount?: number;
		icon?: string;
		id: string;
		location?: string;
		markAsDone?: boolean;
		name: string;
		notifyBefore?: number;
		participants?: string;
		rruleSpec?: string;
		rruleType?: string;
		skip?: boolean;
		title?: string;
		updatedAt?: number;
	}[];
	eventTextColor: DefaultEventTextColor;
	eventTextColorAlt: AlternativeEventTextColor;
	excludedCategorySeriesProps: ExcludedProperties;
	excludedNameSeriesProps: ExcludedProperties1;
	excludedRecurringInstanceProps: ExcludedProperties2;
	/**
	 * Folder where exported .ics files are saved
	 */
	exportFolder: string;
	fileConcurrencyLimit: FileOperationConcurrencyLimit;
	/**
	 * JavaScript expressions to filter events (one per line). Changes apply when you click outside or press Ctrl/Cmd+Enter. Note: Expect a brief lag when applying changes as it triggers full re-indexing.
	 */
	filterExpressions: string[];
	filterPresets: {
		expression: string;
		name: string;
	}[];
	firstDayOfWeek: number;
	frontmatterDisplayProperties: DisplayPropertiesTimedEvents;
	frontmatterDisplayPropertiesAllDay: DisplayPropertiesAllDayEvents;
	frontmatterDisplayPropertiesHeatmap: DisplayPropertiesHeatmap;
	frontmatterDisplayPropertiesUntracked: DisplayPropertiesUntrackedEvents;
	/**
	 * Maximum number of future recurring event instances to generate (1-52)
	 */
	futureInstancesCount: number;
	/**
	 * Frontmatter property name for per-event override of future instances count (defaults to global setting if not specified)
	 */
	futureInstancesCountProp: string;
	ganttContextMenuState?: {
		colorOverrides?: {
			[k: string]: string;
		};
		iconOverrides?: {
			[k: string]: string;
		};
		renames?: {
			[k: string]: string;
		};
		sectionOverrides?: {
			[k: string]: string;
		};
		showSettingsButton?: boolean;
		visibleItemIds?: string[];
	};
	/**
	 * Frontmatter property name for generating past recurring instances from source event start date (set to true to enable)
	 */
	generatePastEventsProp: string;
	heatmapMonthlyStatsGridState?: unknown;
	/**
	 * Hide Saturday and Sunday in calendar views
	 */
	hideWeekends: boolean;
	/**
	 * Subtly highlight events that are currently active (if any), or the next upcoming event. Only visible when the current time is within the visible date range.
	 */
	highlightUpcomingEvent: boolean;
	holidays: {
		country: string;
		enabled: boolean;
		region?: string;
		state?: string;
		timezone?: string;
		types: ("public" | "bank" | "school" | "observance" | "optional")[];
	};
	hourEnd: DayEndHour;
	hourStart: DayStartHour;
	/**
	 * Frontmatter property name for event icon override (emoji or text, takes precedence over integration and recurring icons)
	 */
	iconProp: string;
	icsSubscriptionProp: ICSSubscriptionProperty;
	id: string;
	/**
	 * Index event files in all subdirectories of the configured folder, not just the immediate children. When enabled, events stored at any depth (e.g., courses/CS101/assignments/HW1.md) appear in the planning system. When disabled, only files directly inside the configured folder are indexed.
	 */
	indexSubdirectories: boolean;
	instanceDateProp: RecurringInstanceDateProperty;
	/**
	 * Language and date format for headings, day names, month names, toolbar labels, and date displays
	 */
	locale:
		| "en"
		| "fr"
		| "de"
		| "es"
		| "it"
		| "pt-br"
		| "nl"
		| "ja"
		| "ko"
		| "zh-cn"
		| "zh-tw"
		| "ru"
		| "ar"
		| "pl"
		| "tr"
		| "sv"
		| "da"
		| "fi"
		| "nb";
	/**
	 * Frontmatter property name for event location (single string)
	 */
	locationProp: string;
	markPastInstancesAsDone: MarkPastEventsAsDone;
	/**
	 * Frontmatter property name for per-event notification times (timed events)
	 */
	minutesBeforeProp: string;
	mobileMaxEventsPerDay: MobileEventsPerDay;
	mobileToolbarButtons: (
		| "prevNext"
		| "today"
		| "now"
		| "createEvent"
		| "zoomLevel"
		| "filterPresets"
		| "searchInput"
		| "expressionFilter"
		| "untrackedEvents"
	)[];
	monthEvenColor: string;
	monthlyCalendarStatsGridState?: unknown;
	monthOddColor: string;
	name: string;
	/**
	 * Value to set in the status property when marking an event as not done
	 */
	notDoneValue: string;
	notificationSound: PlayNotificationSound;
	nowIndicator: ShowCurrentTimeIndicator;
	pageHeaderState?: {
		colorOverrides?: {
			[k: string]: string;
		};
		iconOverrides?: {
			[k: string]: string;
		};
		renames?: {
			[k: string]: string;
		};
		showSettingsButton?: boolean;
		visibleActionIds?: string[];
	};
	/**
	 * Frontmatter property name for event participants (array of strings, supports comma-separated in YAML)
	 */
	participantsProp: string;
	/**
	 * Visual contrast of past events (0% = invisible, 100% = normal)
	 */
	pastEventContrast: number;
	/**
	 * Symbol/emoji to display on physical recurring instance events in the top-right corner.
	 */
	physicalRecurringMarker: string;
	/**
	 * Frontmatter property name for event prerequisites (wiki-links to other events that must complete before this event)
	 */
	prerequisiteProp: string;
	/**
	 * Automatically propagate frontmatter changes across events that share the same category. When you update custom properties on one event, all other events with the same category are updated immediately.
	 */
	propagateFrontmatterToCategorySeries: boolean;
	/**
	 * Automatically propagate frontmatter changes from recurring event sources to all physical instances. When you update custom properties (like category, priority, status) in a source event, all existing instances are updated immediately.
	 */
	propagateFrontmatterToInstances: boolean;
	/**
	 * Automatically propagate frontmatter changes across events that share the same title. When you update custom properties on one event, all other events with the same name are updated immediately.
	 */
	propagateFrontmatterToNameSeries: boolean;
	rruleIdProp: RRuleIDProperty;
	rruleProp: RRuleProperty;
	rruleSpecProp: RRuleSpecificationProperty;
	rruleUntilProp: RRuleUntilProperty;
	/**
	 * Show color indicator dots at the top of each day in month and year views
	 */
	showColorDots: boolean;
	/**
	 * Display durations as decimal hours (e.g., 2.5h) instead of formatted (e.g., 2h 30m) in statistics modals. Can be temporarily toggled by clicking the duration in the statistics header.
	 */
	showDecimalHours: boolean;
	/**
	 * Display a duration in minutes field in the event creation/edit modal for quick editing. Changes to duration automatically update the end date, and vice versa.
	 */
	showDurationField: boolean;
	showDurationInTitle: ShowDurationInEventTitle;
	showEventColorDots: ShowOverflowColorDots;
	/**
	 * Display a marker indicator on physical recurring instance events (actual instances created from source).
	 */
	showPhysicalRecurringMarker: boolean;
	/**
	 * Display an icon in the left sidebar to quickly open this planning system
	 */
	showRibbonIcon: boolean;
	/**
	 * Display a marker indicator on source recurring events (the original event that generates instances).
	 */
	showSourceRecurringMarker: boolean;
	showStopwatch: ShowTimeTrackerInEventModal;
	skipNewlyCreatedNotifications: SkipNewlyCreatedEvents;
	/**
	 * Frontmatter property name to hide events from the planning system (when set to true)
	 */
	skipProp: string;
	/**
	 * Hide frontmatter properties that start with underscore (e.g., _ZettelID) in event previews and edit modals
	 */
	skipUnderscoreProperties: boolean;
	/**
	 * Duration of time slots in the calendar grid (1-60 minutes)
	 */
	slotDurationMinutes: number;
	slotEventOverlap: AllowSlotEventOverlap;
	/**
	 * Snap interval when dragging or resizing events (1-60 minutes)
	 */
	snapDurationMinutes: number;
	snoozeMinutes: SnoozeDurationMinutes;
	/**
	 * Frontmatter property to write the normalized datetime to. This is a dedicated sorting property, separate from the Date property used by all-day events.
	 */
	sortDateProp: string;
	sortingStrategy: SortingNormalizationStrategy;
	/**
	 * Frontmatter property name for linking recurring event instances to their source event file
	 */
	sourceProp: string;
	/**
	 * Symbol/emoji to display on source recurring events in the top-right corner.
	 */
	sourceRecurringMarker: string;
	/**
	 * Frontmatter property name for event start date/time
	 */
	startProp: string;
	/**
	 * Frontmatter property name for event status (used when automatically marking past events as done)
	 */
	statusProperty: string;
	/**
	 * Keep all-day event section visible at the top when scrolling down in weekly and daily views
	 */
	stickyAllDayEvents: boolean;
	/**
	 * Keep day/date headers visible at the top when scrolling down in weekly and daily views
	 */
	stickyDayHeaders: boolean;
	/**
	 * Path to Templater template file for new events (optional, requires Templater plugin)
	 */
	templatePath?: string;
	/**
	 * Make full-hour lines (12:00, 13:00, etc.) thicker in day and week views for better visual contrast
	 */
	thickerHourLines: boolean;
	/**
	 * Show inline type-ahead suggestions when typing event titles in the create/edit modal. Suggests categories, event presets, and frequently used event names.
	 */
	titleAutocomplete: boolean;
	/**
	 * Frontmatter property name for event title (optional, defaults to file name)
	 */
	titleProp?: string;
	toolbarButtons: (
		| "prevNext"
		| "today"
		| "now"
		| "createEvent"
		| "zoomLevel"
		| "filterPresets"
		| "searchInput"
		| "expressionFilter"
		| "untrackedEvents"
	)[];
	/**
	 * JavaScript expressions to filter untracked events (one per line). Changes apply when you click outside or press Ctrl/Cmd+Enter.
	 */
	untrackedFilterExpressions: string[];
	/**
	 * File name for the virtual events storage file (without .md extension)
	 */
	virtualEventsFileName: string;
	zettelIdProp?: ZettelIDProperty;
	zoomLevels: ZoomLevelsMinutes;
} | null;
/**
 * Use substring matching (case-insensitive) for category auto-assignment and category assignment presets. When enabled, categories match if the event name contains the category name, and preset event names match if the event name contains the preset name. Example: 'Youtube Analysis' matches the 'Youtube' category and a preset with event name 'Youtube'.
 */
export type SubstringMatchingForCategoriesAndPresets = boolean;
/**
 * Automatically assign a category when the event name (without ZettelID) matches a category name (case-insensitive). Example: creating an event named 'Health' will auto-assign the 'health' category.
 */
export type AutoAssignWhenNameMatchesCategory = boolean;
/**
 * Automatically add a Zettel ID timestamp to filenames of events in the planning system directory that don't have one. Files are renamed from 'My Event.md' to 'My Event-20260216120000.md'.
 */
export type AutoAssignZettelID = "disabled" | "calendarEvents" | "allEvents";
/**
 * Comma-separated list of frontmatter properties to include as columns in Bases views. These properties will appear after the default columns (file name, date, status).
 */
export type AdditionalProperties = string[];
/**
 * Choose the default view type for Bases views (category events, interval views). Cards view displays events as visual cards, table view as a sortable table, and list view as a simple list.
 */
export type ViewType = "table" | "cards" | "list";
/**
 * Frontmatter property name for CalDAV integration metadata on synced events
 */
export type CalDAVProperty = string;
/**
 * Show used vs remaining hours in statistics and page header. Boundaries are inferred from the earliest and latest events in each period.
 */
export type EnableCapacityTracking = boolean;
/**
 * Size of connection arrowheads in pixels
 */
export type ArrowheadSize = number;
/**
 * Color of the prerequisite connection arrows on the Calendar tab
 */
export type ArrowColor = string;
/**
 * Thickness of connection arrow lines in pixels
 */
export type LineThickness = number;
/**
 * Controls the background coloring of day cells. Off: default calendar appearance. Uniform: applies a single gradient color to all day cells. Month boundary: alternates two gradient colors by even/odd month, making month transitions clearly visible.
 */
export type DayCellColoring = "off" | "uniform" | "boundary";
/**
 * Default grouping mode for statistics modals: group by event name or by category
 */
export type DefaultGroupingMode = "name" | "category";
/**
 * Default notification time for all-day events. Leave empty for no default. 0 = notify on the day of the event, 1 = notify 1 day before
 */
export type AllDayEventsDaysBefore = number;
/**
 * Default event duration when only start time is provided
 */
export type DefaultDurationMinutes = number;
/**
 * Default notification time for timed events. Leave empty for no default. 0 = notify when event starts, 15 = notify 15 minutes before
 */
export type TimedEventsMinutesBefore = number;
/**
 * The calendar view to show when opening on mobile devices (screen width ≤ 768px)
 */
export type DefaultMobileView = "multiMonthYear" | "dayGridMonth" | "timeGridWeek" | "timeGridDay" | "listWeek";
/**
 * Default color for events when no color rules match
 */
export type DefaultEventColor = string;
/**
 * The calendar view to show when opening
 */
export type DefaultView = "multiMonthYear" | "dayGridMonth" | "timeGridWeek" | "timeGridDay" | "listWeek";
/**
 * How compact to make the calendar display
 */
export type DisplayDensity = "comfortable" | "compact";
/**
 * Maximum events to show per day on desktop before showing '+more' link (0 = unlimited)
 */
export type DesktopEventsPerDay = number;
/**
 * Maximum number of events to stack vertically before showing '+ more' link
 */
export type EventStackLimit = number;
/**
 * Allow events with overlapping times to render on top of each other. When disabled, overlapping events render side-by-side in columns (like Google Calendar). Applies to all views.
 */
export type AllowEventOverlap = boolean;
/**
 * Text color for events with dark backgrounds (default: white)
 */
export type DefaultEventTextColor = string;
/**
 * Text color used when event background is light or white (e.g., pastel colors) for better contrast
 */
export type AlternativeEventTextColor = string;
/**
 * Comma-separated list of frontmatter property names to exclude when propagating changes across category series members.
 */
export type ExcludedProperties = string;
/**
 * Comma-separated list of frontmatter property names to exclude when propagating changes across name series members.
 */
export type ExcludedProperties1 = string;
/**
 * Comma-separated list of frontmatter property names to exclude when propagating changes from recurring event sources to physical instances.
 */
export type ExcludedProperties2 = string;
/**
 * Maximum number of files to modify in parallel. Lower values reduce the risk of Obsidian freezing on large batch operations. Applies to recurring event propagation, name/category series propagation, and file deletions.
 */
export type FileOperationConcurrencyLimit = number;
/**
 * Comma-separated list of frontmatter property names to display in timed events (events with start and end times). Properties are shown in weekly and daily views, but hidden in monthly view to save space.
 */
export type DisplayPropertiesTimedEvents = string[];
/**
 * Comma-separated list of frontmatter property names to display in all-day events. Properties are shown in weekly and daily views, but hidden in monthly view to save space.
 */
export type DisplayPropertiesAllDayEvents = string[];
/**
 * Comma-separated list of frontmatter property names to display in the heatmap day detail panel when inspecting events. Properties appear below each event title with links rendered interactively.
 */
export type DisplayPropertiesHeatmap = string[];
/**
 * Comma-separated list of frontmatter property names to display in untracked events (events without dates). These appear in the untracked events sidebar.
 */
export type DisplayPropertiesUntrackedEvents = string[];
/**
 * Last hour to show in time grid views
 */
export type DayEndHour = number;
/**
 * First hour to show in time grid views
 */
export type DayStartHour = number;
/**
 * Frontmatter property name for ICS subscription metadata on synced events
 */
export type ICSSubscriptionProperty = string;
/**
 * Frontmatter property name for the date of a physical recurring event instance
 */
export type RecurringInstanceDateProperty = string;
/**
 * Automatically mark past events as done during startup by updating their status property. Configure the status property and done value in the Properties section.
 */
export type MarkPastEventsAsDone = boolean;
/**
 * Maximum events to show per day on mobile before showing '+more' link (0 = unlimited)
 */
export type MobileEventsPerDay = number;
/**
 * Play a system sound when notifications are shown
 */
export type PlayNotificationSound = boolean;
/**
 * Display a line showing the current time in weekly and daily views
 */
export type ShowCurrentTimeIndicator = boolean;
/**
 * Frontmatter property name for recurring event unique identifier
 */
export type RRuleIDProperty = string;
/**
 * Frontmatter property name for recurring event type (daily, weekly, monthly, etc.)
 */
export type RRuleProperty = string;
/**
 * Frontmatter property name for recurring event specification (weekdays for weekly/bi-weekly events)
 */
export type RRuleSpecificationProperty = string;
/**
 * Frontmatter property name for recurring event end date (inclusive last occurrence day)
 */
export type RRuleUntilProperty = string;
/**
 * Display event duration (e.g., 2h 30m) in parentheses after the event title for timed events
 */
export type ShowDurationInEventTitle = boolean;
/**
 * Show color dots in the bottom-right corner of events for matched color rules that were not applied as the event background. Displays overflow colors that exceed the color mode limit, or all matched colors when coloring is disabled.
 */
export type ShowOverflowColorDots = boolean;
/**
 * Display a stopwatch in the event creation/edit modal for precise time tracking. Start fills the start date, stop fills the end date, and break time is tracked automatically.
 */
export type ShowTimeTrackerInEventModal = boolean;
/**
 * Automatically mark events as notified if they were created within the last minute. Prevents notifications for events created via Create Event, Stopwatch, or other creation methods.
 */
export type SkipNewlyCreatedEvents = boolean;
/**
 * In week/day time-grid views, allow events that share the exact same time-slot boundaries to render on top of each other. When disabled, events with identical start/end times are placed in separate columns within the slot. Has no effect when event overlap is disabled.
 */
export type AllowSlotEventOverlap = boolean;
/**
 * How many minutes to snooze a notification when pressing the Snooze button. The notification will be triggered again after this duration.
 */
export type SnoozeDurationMinutes = number;
/**
 * Write a normalized datetime to a dedicated sort property so external tools (Bases, Dataview) can sort all event types by a single field. Timed events use the full datetime. All-day events get T00:00:00 appended for consistent cross-type sorting. The value is written to the sort date property configured below.
 */
export type SortingNormalizationStrategy =
	| "none"
	| "startDate"
	| "endDate"
	| "allDayOnly"
	| "allStartDate"
	| "allEndDate";
/**
 * Frontmatter property name for auto-generated ZettelID (optional, generates timestamp-based ID on creation/cloning)
 */
export type ZettelIDProperty = string;
/**
 * Available zoom levels for Ctrl+scroll zooming. Enter comma-separated values (1-60 minutes each)
 */
export type ZoomLevelsMinutes = number[];
export interface PrismaCalendarGetStatisticsInput {
	calendarId?: string;
	date?: string;
	interval?: "day" | "week" | "month";
	mode?: "name" | "category";
}
export type PrismaCalendarGetStatisticsOutput = {
	allDayEvents: number;
	doneEvents: number;
	entries: {
		count: number;
		duration: number;
		durationFormatted: string;
		isRecurring: boolean;
		name: string;
		percentage: string;
	}[];
	interval: "day" | "week" | "month";
	mode: "name" | "category";
	periodEnd: string;
	periodStart: string;
	skippedEvents: number;
	timedEvents: number;
	totalDuration: number;
	totalDurationFormatted: string;
	totalEvents: number;
	undoneEvents: number;
} | null;
export interface PrismaCalendarGetUntrackedEventsInput {
	calendarId?: string;
}
export type PrismaCalendarGetUntrackedEventsOutput = {
	allDay: boolean;
	categories?: string[];
	color?: string;
	end?: string;
	filePath: string;
	icon?: string;
	instanceDate?: string;
	location?: string;
	participants?: string[];
	rruleId?: string;
	rruleType?: string;
	skipped: boolean;
	start?: string;
	status?: string;
	title: string;
	type: "timed" | "allDay" | "untracked";
	virtualKind: string;
}[];
export type PrismaCalendarIsProOutput = boolean;
export type PrismaCalendarListCalendarsOutput = {
	calendarId: string;
	directory: string;
	enabled: boolean;
	eventCount: number;
	name: string;
	untrackedEventCount: number;
}[];
export interface PrismaCalendarMakeEventRealInput {
	calendarId?: string;
	virtualEventId: string;
}
export type PrismaCalendarMakeEventRealOutput = boolean;
export interface PrismaCalendarMakeEventVirtualInput {
	calendarId?: string;
	filePath: string;
}
export type PrismaCalendarMakeEventVirtualOutput = boolean;
export interface PrismaCalendarMarkAsDoneInput {
	calendarId?: string;
	filePath: string;
}
export type PrismaCalendarMarkAsDoneOutput = boolean;
export interface PrismaCalendarMarkAsUndoneInput {
	calendarId?: string;
	filePath: string;
}
export type PrismaCalendarMarkAsUndoneOutput = boolean;
export interface PrismaCalendarMoveEventInput {
	calendarId?: string;
	filePath: string;
	offsetMs: number;
}
export type PrismaCalendarMoveEventOutput = boolean;
export interface PrismaCalendarMoveEventToCalendarInput {
	calendarId?: string;
	filePath: string;
	targetCalendarId: string;
}
export interface PrismaCalendarMoveEventToCalendarOutput {
	error?: string;
	movedFilePath?: string;
	success: boolean;
}
export interface PrismaCalendarNavigateToDateInput {
	calendarId?: string;
	date?: string;
	view?: string;
}
export type PrismaCalendarNavigateToDateOutput = boolean;
export interface PrismaCalendarOpenCreateEventModalInput {
	autoStartStopwatch?: boolean;
	calendarId?: string;
	openCreatedInNewTab?: boolean;
}
export interface PrismaCalendarOpenEditActiveNoteModalInput {
	calendarId?: string;
}
export interface PrismaCalendarRefreshCalendarInput {
	calendarId?: string;
}
export interface PrismaCalendarToggleSkipInput {
	calendarId?: string;
	filePath: string;
}
export type PrismaCalendarToggleSkipOutput = boolean;
/**
 * Use substring matching (case-insensitive) for category auto-assignment and category assignment presets. When enabled, categories match if the event name contains the category name, and preset event names match if the event name contains the preset name. Example: 'Youtube Analysis' matches the 'Youtube' category and a preset with event name 'Youtube'.
 */

/**
 * Automatically assign a category when the event name (without ZettelID) matches a category name (case-insensitive). Example: creating an event named 'Health' will auto-assign the 'health' category.
 */

/**
 * Automatically add a Zettel ID timestamp to filenames of events in the planning system directory that don't have one. Files are renamed from 'My Event.md' to 'My Event-20260216120000.md'.
 */

/**
 * Comma-separated list of frontmatter properties to include as columns in Bases views. These properties will appear after the default columns (file name, date, status).
 */

/**
 * Choose the default view type for Bases views (category events, interval views). Cards view displays events as visual cards, table view as a sortable table, and list view as a simple list.
 */

/**
 * Frontmatter property name for CalDAV integration metadata on synced events
 */

/**
 * Show used vs remaining hours in statistics and page header. Boundaries are inferred from the earliest and latest events in each period.
 */

/**
 * Size of connection arrowheads in pixels
 */

/**
 * Color of the prerequisite connection arrows on the Calendar tab
 */

/**
 * Thickness of connection arrow lines in pixels
 */

/**
 * Controls the background coloring of day cells. Off: default calendar appearance. Uniform: applies a single gradient color to all day cells. Month boundary: alternates two gradient colors by even/odd month, making month transitions clearly visible.
 */

/**
 * Default grouping mode for statistics modals: group by event name or by category
 */

/**
 * Default notification time for all-day events. Leave empty for no default. 0 = notify on the day of the event, 1 = notify 1 day before
 */

/**
 * Default event duration when only start time is provided
 */

/**
 * Default notification time for timed events. Leave empty for no default. 0 = notify when event starts, 15 = notify 15 minutes before
 */

/**
 * The calendar view to show when opening on mobile devices (screen width ≤ 768px)
 */

/**
 * Default color for events when no color rules match
 */

/**
 * The calendar view to show when opening
 */

/**
 * How compact to make the calendar display
 */

/**
 * Maximum events to show per day on desktop before showing '+more' link (0 = unlimited)
 */

/**
 * Maximum number of events to stack vertically before showing '+ more' link
 */

/**
 * Allow events with overlapping times to render on top of each other. When disabled, overlapping events render side-by-side in columns (like Google Calendar). Applies to all views.
 */

/**
 * Text color for events with dark backgrounds (default: white)
 */

/**
 * Text color used when event background is light or white (e.g., pastel colors) for better contrast
 */

/**
 * Comma-separated list of frontmatter property names to exclude when propagating changes across category series members.
 */

/**
 * Comma-separated list of frontmatter property names to exclude when propagating changes across name series members.
 */

/**
 * Comma-separated list of frontmatter property names to exclude when propagating changes from recurring event sources to physical instances.
 */

/**
 * Maximum number of files to modify in parallel. Lower values reduce the risk of Obsidian freezing on large batch operations. Applies to recurring event propagation, name/category series propagation, and file deletions.
 */

/**
 * Comma-separated list of frontmatter property names to display in timed events (events with start and end times). Properties are shown in weekly and daily views, but hidden in monthly view to save space.
 */

/**
 * Comma-separated list of frontmatter property names to display in all-day events. Properties are shown in weekly and daily views, but hidden in monthly view to save space.
 */

/**
 * Comma-separated list of frontmatter property names to display in the heatmap day detail panel when inspecting events. Properties appear below each event title with links rendered interactively.
 */

/**
 * Comma-separated list of frontmatter property names to display in untracked events (events without dates). These appear in the untracked events sidebar.
 */

/**
 * Last hour to show in time grid views
 */

/**
 * First hour to show in time grid views
 */

/**
 * Frontmatter property name for ICS subscription metadata on synced events
 */

/**
 * Frontmatter property name for the date of a physical recurring event instance
 */

/**
 * Automatically mark past events as done during startup by updating their status property. Configure the status property and done value in the Properties section.
 */

/**
 * Maximum events to show per day on mobile before showing '+more' link (0 = unlimited)
 */

/**
 * Play a system sound when notifications are shown
 */

/**
 * Display a line showing the current time in weekly and daily views
 */

/**
 * Frontmatter property name for recurring event unique identifier
 */

/**
 * Frontmatter property name for recurring event type (daily, weekly, monthly, etc.)
 */

/**
 * Frontmatter property name for recurring event specification (weekdays for weekly/bi-weekly events)
 */

/**
 * Frontmatter property name for recurring event end date (inclusive last occurrence day)
 */

/**
 * Display event duration (e.g., 2h 30m) in parentheses after the event title for timed events
 */

/**
 * Show color dots in the bottom-right corner of events for matched color rules that were not applied as the event background. Displays overflow colors that exceed the color mode limit, or all matched colors when coloring is disabled.
 */

/**
 * Display a stopwatch in the event creation/edit modal for precise time tracking. Start fills the start date, stop fills the end date, and break time is tracked automatically.
 */

/**
 * Automatically mark events as notified if they were created within the last minute. Prevents notifications for events created via Create Event, Stopwatch, or other creation methods.
 */

/**
 * In week/day time-grid views, allow events that share the exact same time-slot boundaries to render on top of each other. When disabled, events with identical start/end times are placed in separate columns within the slot. Has no effect when event overlap is disabled.
 */

/**
 * How many minutes to snooze a notification when pressing the Snooze button. The notification will be triggered again after this duration.
 */

/**
 * Write a normalized datetime to a dedicated sort property so external tools (Bases, Dataview) can sort all event types by a single field. Timed events use the full datetime. All-day events get T00:00:00 appended for consistent cross-type sorting. The value is written to the sort date property configured below.
 */

/**
 * Frontmatter property name for auto-generated ZettelID (optional, generates timestamp-based ID on creation/cloning)
 */

/**
 * Available zoom levels for Ctrl+scroll zooming. Enter comma-separated values (1-60 minutes each)
 */

export interface PrismaCalendarUpdateSettingsInput {
	calendarId?: string;
	settings: {
		activeTab?: {
			colorOverrides?: {
				[k: string]: string;
			};
			groupState?: {
				[k: string]: {
					childColorOverrides?: {
						[k: string]: string;
					};
					childIconOverrides?: {
						[k: string]: string;
					};
					childRenames?: {
						[k: string]: string;
					};
					visibleChildIds?: string[];
				};
			};
			iconOverrides?: {
				[k: string]: string;
			};
			renames?: {
				[k: string]: string;
			};
			showSettingsButton?: boolean;
			visibleTabIds?: string[];
		};
		/**
		 * Maximum height in pixels for all-day events section before overflow
		 */
		allDayEventHeight?: number;
		/**
		 * Frontmatter property name for all-day flag
		 */
		allDayProp?: string;
		/**
		 * Frontmatter property name to mark events as already notified
		 */
		alreadyNotifiedProp?: string;
		/**
		 * Show a confirmation modal before propagating frontmatter changes to instances. Allows you to review changes before applying them.
		 */
		askBeforePropagatingFrontmatter?: boolean;
		/**
		 * Show a confirmation modal before propagating frontmatter changes to category series members. Allows you to review changes before applying them.
		 */
		askBeforePropagatingToCategorySeries?: boolean;
		/**
		 * Show a confirmation modal before propagating frontmatter changes to name series members. Allows you to review changes before applying them.
		 */
		askBeforePropagatingToNameSeries?: boolean;
		autoAssignCategoryByIncludes?: SubstringMatchingForCategoriesAndPresets;
		autoAssignCategoryByName?: AutoAssignWhenNameMatchesCategory;
		autoAssignZettelId?: AutoAssignZettelID;
		basesViewProperties?: AdditionalProperties;
		basesViewType?: ViewType;
		batchActionButtons?: (
			| "batchSelectAll"
			| "batchClear"
			| "batchDuplicate"
			| "batchMoveBy"
			| "batchMarkAsDone"
			| "batchMarkAsNotDone"
			| "batchCategories"
			| "batchFrontmatter"
			| "batchCloneNext"
			| "batchClonePrev"
			| "batchMoveNext"
			| "batchMovePrev"
			| "batchOpenAll"
			| "batchSkip"
			| "batchMakeVirtual"
			| "batchMakeReal"
			| "batchDelete"
		)[];
		/**
		 * Frontmatter property name for break time in minutes (subtracted from event duration in statistics, supports decimals)
		 */
		breakProp?: string;
		caldavProp?: CalDAVProperty;
		/**
		 * Auto-computed display title property (wiki link with ZettelID stripped from filename). Used for clean rendering in planning system and Bases views. The value is always kept up to date automatically.
		 */
		calendarTitleProp?: string;
		capacityTrackingEnabled?: EnableCapacityTracking;
		categoryAssignmentPresets?: {
			categories: string[];
			eventName: string;
			id: string;
		}[];
		/**
		 * Frontmatter property name for event categories (used for grouping in statistics)
		 */
		categoryProp?: string;
		/**
		 * Controls how many color rule matches are applied to each event. Off: no coloring. 1: single color (default). 2-5: split the event width into equal segments, each colored by a successive matching rule.
		 */
		colorMode?: "1" | "2" | "3" | "4" | "5" | "off";
		colorRules?: {
			color: string;
			enabled: boolean;
			expression: string;
			id: string;
		}[];
		connectionArrowSize?: ArrowheadSize;
		connectionColor?: ArrowColor;
		connectionStrokeWidth?: LineThickness;
		contextMenuItems?: (
			| "enlarge"
			| "preview"
			| "goToSource"
			| "editSourceEvent"
			| "viewEventGroups"
			| "viewNameSeries"
			| "viewCategorySeries"
			| "viewRecurringSeries"
			| "editEvent"
			| "assignCategories"
			| "assignPrerequisites"
			| "duplicateEvent"
			| "moveBy"
			| "moveToCalendar"
			| "markDone"
			| "moveToNextWeek"
			| "cloneToNextWeek"
			| "moveToPreviousWeek"
			| "cloneToPreviousWeek"
			| "fillStartTimeNow"
			| "fillEndTimeNow"
			| "fillStartTimePrevious"
			| "fillEndTimeNext"
			| "deleteEvent"
			| "skipEvent"
			| "openFile"
			| "openFileNewWindow"
			| "toggleRecurring"
			| "triggerStopwatch"
			| "duplicateRemainingWeekDays"
			| "makeVirtual"
			| "makeReal"
			| "makeUntracked"
		)[];
		contextMenuState?: {
			colorOverrides?: {
				[k: string]: string;
			};
			iconOverrides?: {
				[k: string]: string;
			};
			renames?: {
				[k: string]: string;
			};
			sectionOverrides?: {
				[k: string]: string;
			};
			showSettingsButton?: boolean;
			visibleItemIds?: string[];
		};
		/**
		 * Overrides the status property for manual mark-as-done actions. Format: "propertyName value" (e.g., "archived true"). When set, this is used instead of the status property. Leave empty to use the default behavior.
		 */
		customDoneProperty?: string;
		/**
		 * Overrides what happens when marking as undone. Format: "propertyName value" (e.g., "archived false"). Requires "Custom done property" to be configured. If empty, the custom done property key is removed on undone instead.
		 */
		customUndoneProperty?: string;
		dailyStatsGridState?: unknown;
		dashboardGridState?: {
			[k: string]: unknown;
		};
		/**
		 * Frontmatter property name for all-day events (date only, no time)
		 */
		dateProp?: string;
		dayCellColoring?: DayCellColoring;
		/**
		 * Frontmatter property name for per-event notification days (all-day events)
		 */
		daysBeforeProp?: string;
		defaultAggregationMode?: DefaultGroupingMode;
		defaultDaysBefore?: AllDayEventsDaysBefore;
		defaultDurationMinutes?: DefaultDurationMinutes;
		defaultMinutesBefore?: TimedEventsMinutesBefore;
		defaultMobileView?: DefaultMobileView;
		defaultNodeColor?: DefaultEventColor;
		defaultPresetId?: string;
		defaultView?: DefaultView;
		density?: DisplayDensity;
		desktopMaxEventsPerDay?: DesktopEventsPerDay;
		/**
		 * Folder to scan for events and create new events in
		 */
		directory?: {
			[k: string]: unknown;
		};
		/**
		 * Value to set in the status property when marking an event as done
		 */
		doneValue?: string;
		/**
		 * Delay in milliseconds before scrolling when dragging events near the edge
		 */
		dragEdgeScrollDelayMs?: number;
		dualDailyGridState?: unknown;
		enabled?: boolean;
		/**
		 * Show preview of event notes when hovering over events
		 */
		enableEventPreview?: boolean;
		/**
		 * Use left/right arrow keys to navigate between intervals. Automatically disabled when search or expression filter inputs are focused.
		 */
		enableKeyboardNavigation?: boolean;
		/**
		 * Track name-based event series (groups events sharing the same title). Used for name series propagation and series views. Disable to reduce memory usage in large vaults.
		 */
		enableNameSeriesTracking?: boolean;
		/**
		 * Enable event notifications. When disabled, all notification settings below are ignored.
		 */
		enableNotifications?: boolean;
		/**
		 * Frontmatter property name for event end date/time (for timed events)
		 */
		endProp?: string;
		eventMaxStack?: EventStackLimit;
		eventOverlap?: AllowEventOverlap;
		eventPresets?: {
			allDay?: boolean;
			breakMinutes?: number;
			categories?: string;
			createdAt: number;
			customProperties?: {
				[k: string]: unknown;
			};
			futureInstancesCount?: number;
			icon?: string;
			id: string;
			location?: string;
			markAsDone?: boolean;
			name: string;
			notifyBefore?: number;
			participants?: string;
			rruleSpec?: string;
			rruleType?: string;
			skip?: boolean;
			title?: string;
			updatedAt?: number;
		}[];
		eventTextColor?: DefaultEventTextColor;
		eventTextColorAlt?: AlternativeEventTextColor;
		excludedCategorySeriesProps?: ExcludedProperties;
		excludedNameSeriesProps?: ExcludedProperties1;
		excludedRecurringInstanceProps?: ExcludedProperties2;
		/**
		 * Folder where exported .ics files are saved
		 */
		exportFolder?: string;
		fileConcurrencyLimit?: FileOperationConcurrencyLimit;
		/**
		 * JavaScript expressions to filter events (one per line). Changes apply when you click outside or press Ctrl/Cmd+Enter. Note: Expect a brief lag when applying changes as it triggers full re-indexing.
		 */
		filterExpressions?: string[];
		filterPresets?: {
			expression: string;
			name: string;
		}[];
		firstDayOfWeek?: number;
		frontmatterDisplayProperties?: DisplayPropertiesTimedEvents;
		frontmatterDisplayPropertiesAllDay?: DisplayPropertiesAllDayEvents;
		frontmatterDisplayPropertiesHeatmap?: DisplayPropertiesHeatmap;
		frontmatterDisplayPropertiesUntracked?: DisplayPropertiesUntrackedEvents;
		/**
		 * Maximum number of future recurring event instances to generate (1-52)
		 */
		futureInstancesCount?: number;
		/**
		 * Frontmatter property name for per-event override of future instances count (defaults to global setting if not specified)
		 */
		futureInstancesCountProp?: string;
		ganttContextMenuState?: {
			colorOverrides?: {
				[k: string]: string;
			};
			iconOverrides?: {
				[k: string]: string;
			};
			renames?: {
				[k: string]: string;
			};
			sectionOverrides?: {
				[k: string]: string;
			};
			showSettingsButton?: boolean;
			visibleItemIds?: string[];
		};
		/**
		 * Frontmatter property name for generating past recurring instances from source event start date (set to true to enable)
		 */
		generatePastEventsProp?: string;
		heatmapMonthlyStatsGridState?: unknown;
		/**
		 * Hide Saturday and Sunday in calendar views
		 */
		hideWeekends?: boolean;
		/**
		 * Subtly highlight events that are currently active (if any), or the next upcoming event. Only visible when the current time is within the visible date range.
		 */
		highlightUpcomingEvent?: boolean;
		holidays?: {
			country: string;
			enabled: boolean;
			region?: string;
			state?: string;
			timezone?: string;
			types: ("public" | "bank" | "school" | "observance" | "optional")[];
		};
		hourEnd?: DayEndHour;
		hourStart?: DayStartHour;
		/**
		 * Frontmatter property name for event icon override (emoji or text, takes precedence over integration and recurring icons)
		 */
		iconProp?: string;
		icsSubscriptionProp?: ICSSubscriptionProperty;
		id?: string;
		/**
		 * Index event files in all subdirectories of the configured folder, not just the immediate children. When enabled, events stored at any depth (e.g., courses/CS101/assignments/HW1.md) appear in the planning system. When disabled, only files directly inside the configured folder are indexed.
		 */
		indexSubdirectories?: boolean;
		instanceDateProp?: RecurringInstanceDateProperty;
		/**
		 * Language and date format for headings, day names, month names, toolbar labels, and date displays
		 */
		locale?:
			| "en"
			| "fr"
			| "de"
			| "es"
			| "it"
			| "pt-br"
			| "nl"
			| "ja"
			| "ko"
			| "zh-cn"
			| "zh-tw"
			| "ru"
			| "ar"
			| "pl"
			| "tr"
			| "sv"
			| "da"
			| "fi"
			| "nb";
		/**
		 * Frontmatter property name for event location (single string)
		 */
		locationProp?: string;
		markPastInstancesAsDone?: MarkPastEventsAsDone;
		/**
		 * Frontmatter property name for per-event notification times (timed events)
		 */
		minutesBeforeProp?: string;
		mobileMaxEventsPerDay?: MobileEventsPerDay;
		mobileToolbarButtons?: (
			| "prevNext"
			| "today"
			| "now"
			| "createEvent"
			| "zoomLevel"
			| "filterPresets"
			| "searchInput"
			| "expressionFilter"
			| "untrackedEvents"
		)[];
		monthEvenColor?: string;
		monthlyCalendarStatsGridState?: unknown;
		monthOddColor?: string;
		name?: string;
		/**
		 * Value to set in the status property when marking an event as not done
		 */
		notDoneValue?: string;
		notificationSound?: PlayNotificationSound;
		nowIndicator?: ShowCurrentTimeIndicator;
		pageHeaderState?: {
			colorOverrides?: {
				[k: string]: string;
			};
			iconOverrides?: {
				[k: string]: string;
			};
			renames?: {
				[k: string]: string;
			};
			showSettingsButton?: boolean;
			visibleActionIds?: string[];
		};
		/**
		 * Frontmatter property name for event participants (array of strings, supports comma-separated in YAML)
		 */
		participantsProp?: string;
		/**
		 * Visual contrast of past events (0% = invisible, 100% = normal)
		 */
		pastEventContrast?: number;
		/**
		 * Symbol/emoji to display on physical recurring instance events in the top-right corner.
		 */
		physicalRecurringMarker?: string;
		/**
		 * Frontmatter property name for event prerequisites (wiki-links to other events that must complete before this event)
		 */
		prerequisiteProp?: string;
		/**
		 * Automatically propagate frontmatter changes across events that share the same category. When you update custom properties on one event, all other events with the same category are updated immediately.
		 */
		propagateFrontmatterToCategorySeries?: boolean;
		/**
		 * Automatically propagate frontmatter changes from recurring event sources to all physical instances. When you update custom properties (like category, priority, status) in a source event, all existing instances are updated immediately.
		 */
		propagateFrontmatterToInstances?: boolean;
		/**
		 * Automatically propagate frontmatter changes across events that share the same title. When you update custom properties on one event, all other events with the same name are updated immediately.
		 */
		propagateFrontmatterToNameSeries?: boolean;
		rruleIdProp?: RRuleIDProperty;
		rruleProp?: RRuleProperty;
		rruleSpecProp?: RRuleSpecificationProperty;
		rruleUntilProp?: RRuleUntilProperty;
		/**
		 * Show color indicator dots at the top of each day in month and year views
		 */
		showColorDots?: boolean;
		/**
		 * Display durations as decimal hours (e.g., 2.5h) instead of formatted (e.g., 2h 30m) in statistics modals. Can be temporarily toggled by clicking the duration in the statistics header.
		 */
		showDecimalHours?: boolean;
		/**
		 * Display a duration in minutes field in the event creation/edit modal for quick editing. Changes to duration automatically update the end date, and vice versa.
		 */
		showDurationField?: boolean;
		showDurationInTitle?: ShowDurationInEventTitle;
		showEventColorDots?: ShowOverflowColorDots;
		/**
		 * Display a marker indicator on physical recurring instance events (actual instances created from source).
		 */
		showPhysicalRecurringMarker?: boolean;
		/**
		 * Display an icon in the left sidebar to quickly open this planning system
		 */
		showRibbonIcon?: boolean;
		/**
		 * Display a marker indicator on source recurring events (the original event that generates instances).
		 */
		showSourceRecurringMarker?: boolean;
		showStopwatch?: ShowTimeTrackerInEventModal;
		skipNewlyCreatedNotifications?: SkipNewlyCreatedEvents;
		/**
		 * Frontmatter property name to hide events from the planning system (when set to true)
		 */
		skipProp?: string;
		/**
		 * Hide frontmatter properties that start with underscore (e.g., _ZettelID) in event previews and edit modals
		 */
		skipUnderscoreProperties?: boolean;
		/**
		 * Duration of time slots in the calendar grid (1-60 minutes)
		 */
		slotDurationMinutes?: number;
		slotEventOverlap?: AllowSlotEventOverlap;
		/**
		 * Snap interval when dragging or resizing events (1-60 minutes)
		 */
		snapDurationMinutes?: number;
		snoozeMinutes?: SnoozeDurationMinutes;
		/**
		 * Frontmatter property to write the normalized datetime to. This is a dedicated sorting property, separate from the Date property used by all-day events.
		 */
		sortDateProp?: string;
		sortingStrategy?: SortingNormalizationStrategy;
		/**
		 * Frontmatter property name for linking recurring event instances to their source event file
		 */
		sourceProp?: string;
		/**
		 * Symbol/emoji to display on source recurring events in the top-right corner.
		 */
		sourceRecurringMarker?: string;
		/**
		 * Frontmatter property name for event start date/time
		 */
		startProp?: string;
		/**
		 * Frontmatter property name for event status (used when automatically marking past events as done)
		 */
		statusProperty?: string;
		/**
		 * Keep all-day event section visible at the top when scrolling down in weekly and daily views
		 */
		stickyAllDayEvents?: boolean;
		/**
		 * Keep day/date headers visible at the top when scrolling down in weekly and daily views
		 */
		stickyDayHeaders?: boolean;
		/**
		 * Path to Templater template file for new events (optional, requires Templater plugin)
		 */
		templatePath?: string;
		/**
		 * Make full-hour lines (12:00, 13:00, etc.) thicker in day and week views for better visual contrast
		 */
		thickerHourLines?: boolean;
		/**
		 * Show inline type-ahead suggestions when typing event titles in the create/edit modal. Suggests categories, event presets, and frequently used event names.
		 */
		titleAutocomplete?: boolean;
		/**
		 * Frontmatter property name for event title (optional, defaults to file name)
		 */
		titleProp?: string;
		toolbarButtons?: (
			| "prevNext"
			| "today"
			| "now"
			| "createEvent"
			| "zoomLevel"
			| "filterPresets"
			| "searchInput"
			| "expressionFilter"
			| "untrackedEvents"
		)[];
		/**
		 * JavaScript expressions to filter untracked events (one per line). Changes apply when you click outside or press Ctrl/Cmd+Enter.
		 */
		untrackedFilterExpressions?: string[];
		/**
		 * File name for the virtual events storage file (without .md extension)
		 */
		virtualEventsFileName?: string;
		zettelIdProp?: ZettelIDProperty;
		zoomLevels?: ZoomLevelsMinutes;
	};
}
export type PrismaCalendarUpdateSettingsOutput = boolean;
export interface PrismaCalendarApi {
	activate(input: PrismaCalendarActivateInput): Promise<void>;
	addZettelIdToActiveNote(
		input: PrismaCalendarAddZettelIdToActiveNoteInput
	): Promise<PrismaCalendarAddZettelIdToActiveNoteOutput>;
	aiQuery(input: PrismaCalendarAiQueryInput): Promise<PrismaCalendarAiQueryOutput>;
	batchDelete(input: PrismaCalendarBatchDeleteInput): Promise<PrismaCalendarBatchDeleteOutput>;
	batchMarkAsDone(input: PrismaCalendarBatchMarkAsDoneInput): Promise<PrismaCalendarBatchMarkAsDoneOutput>;
	batchMarkAsUndone(input: PrismaCalendarBatchMarkAsUndoneInput): Promise<PrismaCalendarBatchMarkAsUndoneOutput>;
	batchToggleSkip(input: PrismaCalendarBatchToggleSkipInput): Promise<PrismaCalendarBatchToggleSkipOutput>;
	cloneEvent(input: PrismaCalendarCloneEventInput): Promise<PrismaCalendarCloneEventOutput>;
	convertFileToEvent(input: PrismaCalendarConvertFileToEventInput): Promise<PrismaCalendarConvertFileToEventOutput>;
	createEvent(input: PrismaCalendarCreateEventInput): Promise<PrismaCalendarCreateEventOutput>;
	createUntrackedEvent(
		input: PrismaCalendarCreateUntrackedEventInput
	): Promise<PrismaCalendarCreateUntrackedEventOutput>;
	deleteEvent(input: PrismaCalendarDeleteEventInput): Promise<PrismaCalendarDeleteEventOutput>;
	duplicateCurrentEvent(
		input: PrismaCalendarDuplicateCurrentEventInput
	): Promise<PrismaCalendarDuplicateCurrentEventOutput>;
	editEvent(input: PrismaCalendarEditEventInput): Promise<PrismaCalendarEditEventOutput>;
	getAllEvents(input: PrismaCalendarGetAllEventsInput): Promise<PrismaCalendarGetAllEventsOutput>;
	getCalendarInfo(input: PrismaCalendarGetCalendarInfoInput): Promise<PrismaCalendarGetCalendarInfoOutput>;
	getCategories(input: PrismaCalendarGetCategoriesInput): Promise<PrismaCalendarGetCategoriesOutput>;
	getEventByPath(input: PrismaCalendarGetEventByPathInput): Promise<PrismaCalendarGetEventByPathOutput>;
	getEvents(input: PrismaCalendarGetEventsInput): Promise<PrismaCalendarGetEventsOutput>;
	getSettings(input: PrismaCalendarGetSettingsInput): Promise<PrismaCalendarGetSettingsOutput>;
	getStatistics(input: PrismaCalendarGetStatisticsInput): Promise<PrismaCalendarGetStatisticsOutput>;
	getUntrackedEvents(input: PrismaCalendarGetUntrackedEventsInput): Promise<PrismaCalendarGetUntrackedEventsOutput>;
	isPro(): Promise<PrismaCalendarIsProOutput>;
	listCalendars(): Promise<PrismaCalendarListCalendarsOutput>;
	makeEventReal(input: PrismaCalendarMakeEventRealInput): Promise<PrismaCalendarMakeEventRealOutput>;
	makeEventVirtual(input: PrismaCalendarMakeEventVirtualInput): Promise<PrismaCalendarMakeEventVirtualOutput>;
	markAsDone(input: PrismaCalendarMarkAsDoneInput): Promise<PrismaCalendarMarkAsDoneOutput>;
	markAsUndone(input: PrismaCalendarMarkAsUndoneInput): Promise<PrismaCalendarMarkAsUndoneOutput>;
	moveEvent(input: PrismaCalendarMoveEventInput): Promise<PrismaCalendarMoveEventOutput>;
	moveEventToCalendar(input: PrismaCalendarMoveEventToCalendarInput): Promise<PrismaCalendarMoveEventToCalendarOutput>;
	navigateToDate(input: PrismaCalendarNavigateToDateInput): Promise<PrismaCalendarNavigateToDateOutput>;
	openCreateEventModal(input: PrismaCalendarOpenCreateEventModalInput): Promise<void>;
	openEditActiveNoteModal(input: PrismaCalendarOpenEditActiveNoteModalInput): Promise<void>;
	refreshCalendar(input: PrismaCalendarRefreshCalendarInput): Promise<void>;
	toggleSkip(input: PrismaCalendarToggleSkipInput): Promise<PrismaCalendarToggleSkipOutput>;
	updateSettings(input: PrismaCalendarUpdateSettingsInput): Promise<PrismaCalendarUpdateSettingsOutput>;
}

declare global {
	interface Window {
		PrismaCalendar?: PrismaCalendarApi;
	}
}
