import { existsSync, readFileSync } from "node:fs";
import { builtinModules, createRequire } from "node:module";
import path from "node:path";

import type { Plugin, UserConfig } from "vite";

const require = createRequire(import.meta.url);

// `createRequire` sidesteps ESM/CJS interop quirks for CJS-shaped Vite plugin
// packages; otherwise the default export resolution differs depending on whether
// the calling plugin's package.json declares `"type": "module"`.
function loadDefault<T>(specifier: string): T {
	const mod = require(specifier);
	return (mod && typeof mod === "object" && "default" in mod ? mod.default : mod) as T;
}

const babel = loadDefault<(options: unknown) => Plugin>("vite-plugin-babel");
const react = loadDefault<(options?: unknown) => Plugin>("@vitejs/plugin-react");
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const DEFAULT_EXTERNALS = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

const BANNER = `/*!
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

interface ObsidianPluginConfigInput {
	pluginDir: string;
	entry?: string;
	extraExternals?: string[];
	resolveAliases?: Record<string, string>;
	reactCompiler?:
		| false
		| {
				compilationMode?: "annotation" | "infer" | "syntax" | "all";
				panicThreshold?: "all_errors" | "critical_errors" | "none";
		  };
}

// React 19 bakes three dynamic-script-creation sites into every react-dom CJS
// bundle: `preinitScript` and `preinitModuleScript` use `createElement("script")`
// directly, and the `case "script":` branch of `createInstance` builds a script
// element via the well-known `div.<HTML-property> = "<script>\x3c/script>"`
// trick (used to bypass auto-execution of inline scripts). Those branches only
// fire when application code renders <script> JSX or calls
// `ReactDOM.preinit*()` — neither happens in an Obsidian plugin. Obsidian's
// plugin review treats all three as dynamic-script-injection errors, so we
// neutralize them at bundle time by rewriting both the createElement type and
// the HTML literal to inert `template` equivalents. The runtime never reaches
// these paths, so neutralizing them is safe.
const REACT_DOM_FILE =
	/[\\/]react-dom[\\/]cjs[\\/]react-dom-(client|profiling)\.(production|development|profiling)\.js$/;
const REACT_SCRIPT_HTML_LITERAL = '"<script>\\x3c/script>"';
const REACT_INERT_HTML_LITERAL = '"<template></template>"';
function stripReactScriptInjection(): Plugin {
	return {
		name: "obsidian-no-react-script-injection",
		enforce: "pre",
		transform(code, id) {
			if (!REACT_DOM_FILE.test(id)) return null;
			let next = code;
			if (next.includes('createElement("script")')) {
				next = next.replaceAll('createElement("script")', 'createElement("template")');
			}
			if (next.includes(REACT_SCRIPT_HTML_LITERAL)) {
				next = next.replaceAll(REACT_SCRIPT_HTML_LITERAL, REACT_INERT_HTML_LITERAL);
			}
			return next === code ? null : { code: next, map: null };
		},
	};
}

// Hard guard: fail the build if any dynamic-script-creation pattern survives
// the strip plugin in the final bundle. Runs at `generateBundle` so it sees
// the post-minification output. Catches the case where React DOM changes its
// internal shape (e.g. a future version uses different quote style or a new
// injection trick) and `stripReactScriptInjection` silently no-ops.
//
// Failure mode by design: if this fires, the build aborts with a pointer to
// `stripReactScriptInjection` so the regex / literal there can be updated
// before the broken bundle ships.
const CREATE_ELEMENT_SCRIPT_RE = /createElement\s*\(\s*[`"']script[`"']\s*\)/;
function assertNoReactScriptInjection(): Plugin {
	return {
		name: "obsidian-assert-no-script-injection",
		generateBundle(_options, bundle) {
			for (const [fileName, asset] of Object.entries(bundle)) {
				if (asset.type !== "chunk") continue;
				const code = asset.code;
				const findings: string[] = [];
				if (CREATE_ELEMENT_SCRIPT_RE.test(code)) {
					findings.push("createElement(<quote>script<quote>) — call site (likely React DOM)");
				}
				// Any `<script` substring catches every quote variant of the
				// HTML-literal injection trick (innerHTML / outerHTML / similar
				// sinks). The `[\s/>]` guard prevents false positives on names
				// like `<scripts` while still matching the `<script` opening tag
				// across every valid separator (space, tab, newline, `/`, `>`).
				// The `i` flag also catches `<SCRIPT`.
				if (/<script[\s/>]/i.test(code)) {
					findings.push("<script HTML literal — innerHTML/outerHTML/script-tag injection");
				}
				if (findings.length > 0) {
					this.error(
						`Forbidden dynamic-script-creation patterns survived stripReactScriptInjection in ${fileName}:\n` +
							findings.map((f) => `  - ${f}`).join("\n") +
							"\n\nReact DOM probably changed its internal shape. Update " +
							"`stripReactScriptInjection` in shared/configs/vite-plugin-config.ts so " +
							"the new patterns are neutralized, then re-run the build."
					);
				}
			}
		},
	};
}

function obsidianAssets(pluginDir: string): Plugin[] {
	return [
		{
			name: "obsidian-resolve-plugin-changelog",
			enforce: "pre",
			resolveId(source) {
				if (source.endsWith("/docs-site/docs/changelog.md")) {
					return path.resolve(pluginDir, "docs-site/docs/changelog.md");
				}
				return null;
			},
		},
		{
			name: "obsidian-md-as-string",
			enforce: "pre",
			transform(_code, id) {
				if (!id.endsWith(".md")) return null;
				const raw = readFileSync(id, "utf-8");
				return { code: `export default ${JSON.stringify(raw)};`, map: null };
			},
		},
	];
}

export function obsidianPluginConfig(input: ObsidianPluginConfigInput): (env: { mode: string }) => UserConfig {
	const {
		pluginDir,
		entry = path.resolve(pluginDir, "src/main.ts"),
		extraExternals = [],
		resolveAliases = {},
		reactCompiler = { compilationMode: "annotation", panicThreshold: "none" },
	} = input;

	// Monorepo: pluginDir/<plugin>, shared lives as a sibling at pluginDir/../shared.
	// Mirror: pluginDir is the repo root and shared/ is nested at pluginDir/shared.
	// Detect by probing for shared/ inside pluginDir first, otherwise fall back
	// to the sibling layout used during in-monorepo development.
	const sharedRoot = existsSync(path.resolve(pluginDir, "shared", "src", "index.ts"))
		? pluginDir
		: path.resolve(pluginDir, "..");
	const defaultAliases = {
		"@real1ty-obsidian-plugins-react": path.resolve(sharedRoot, "shared-react/src/index.ts"),
		"@real1ty-obsidian-plugins": path.resolve(sharedRoot, "shared/src/index.ts"),
	};

	return ({ mode }) => {
		const isDev = mode === "development";
		const babelPlugins: Array<unknown> = [];
		if (reactCompiler !== false) {
			babelPlugins.push(["babel-plugin-react-compiler", reactCompiler]);
		}

		const plugins: Plugin[] = [
			...(reactCompiler === false
				? []
				: [
						babel({
							include: /\.[jt]sx?$/,
							babelConfig: {
								babelrc: false,
								configFile: false,
								presets: [["@babel/preset-typescript", { isTSX: true, allExtensions: true }]],
								plugins: babelPlugins,
							},
						}),
					]),
			react(),
			stripReactScriptInjection(),
			assertNoReactScriptInjection(),
			...obsidianAssets(pluginDir),
		];

		return {
			plugins,
			define: {
				"process.env.NODE_ENV": JSON.stringify(isDev ? "development" : "production"),
			},
			resolve: {
				alias: { ...defaultAliases, ...resolveAliases },
			},
			build: {
				target: "es2018",
				outDir: pluginDir,
				emptyOutDir: false,
				// Dev builds inline a sourcemap for debugging. Released/e2e builds ship
				// none. Stress builds opt in with `OBSIDIAN_SOURCEMAP=1` → an external
				// `main.js.map` ("hidden": file emitted, no `sourceMappingURL` comment
				// appended, so the shipped bundle is unchanged) that the CPU-profile
				// digest reads to name minified plugin frames. See the stress real-load spec.
				sourcemap: isDev ? "inline" : process.env["OBSIDIAN_SOURCEMAP"] === "1" ? "hidden" : false,
				minify: !isDev,
				assetsInlineLimit: Number.POSITIVE_INFINITY,
				lib: {
					entry,
					formats: ["cjs"],
					fileName: () => "main.js",
				},
				rollupOptions: {
					external: [...DEFAULT_EXTERNALS, ...extraExternals, ...builtins],
					output: {
						banner: BANNER,
						exports: "default",
						inlineDynamicImports: true,
					},
				},
			},
		};
	};
}
